### PR TITLE
ft: delete user plugin

### PR DESCRIPTION
**Pull request by SooditK**
### Adds a Delete User Plugin

it takes a parameter, whether the organization plugin is being used

if there are organizations associated to the user, the user will not be marked as deleted

P.S. Please ignore `pnpm-lock.yaml`

### CODE REVIEW

**Comment by Bekacru** [comment]
Hey, sorry but could you implement soft delete directly in the core instead of as a plugin? Add an option to choose between hard and soft delete. For soft deletes, we’ll need an extra field in the core with a `deletedAt` column instead of `isDeleted`.

**Comment by Bekacru** [comment]
And there is already hard delete in the core

**Comment by SooditK** [comment]
Hii @Bekacru no worries, I'd be happy to implement it in the core
I'm still not sure that why do we need a separate table for this, we can easily update either the `user` or `account` table with the `isDeleted` boolean flag

one more thing - if we do it in a separate `deleted` table, then every time we fetch/sign-in as a user, then we need to do an extra join to check if the user is deleted or not

let me know your thoughts

**Comment by Bekacru** [comment]
> Hii @Bekacru no worries, I'd be happy to implement it in the core
> 
> I'm still not sure that why do we need a separate table for this, we can easily update either the `user` or `account` table with the `isDeleted` boolean flag
> 
> 
> 
> one more thing - if we do it in a separate `deleted` table, then every time we fetch/sign-in as a user, then we need to do an extra join to check if the user is deleted or not
> 
> 
> 
> let me know your thoughts

Sorry I meant extra field

**Pull request closed without merging**
