### PR TITLE
docs: add TanStack Start integration page

### PR DESCRIPTION
**Pull request by LovelessCodes**
This is an integration page for better auth & [TanStack Start](https://tanstack.com/start/latest)

### CODE REVIEW

**Comment by Bekacru** [comment]
Hey, thanks for this PR! Just additional request: could you create a simple example project for TanStack? a login, user card and signout should be enough

**Comment by LovelessCodes** [comment]
Hey @Bekacru I've added an example project with signup, signin, user details & signout    
As well as added tanstack-start to installation page

**Comment by Bekacru** [comment]
thanks so much. this looks great! can you fix the conflict so I can merge it?

**Comment by LovelessCodes** [comment]
Should be fixed, as well as expanded.

**Pull request merged**
