### PR TITLE
docs: add basic remix documentation

### PR DESCRIPTION
**Pull request by Eiley2**
This closes https://github.com/better-auth/better-auth/issues/9#issuecomment-2380416415

I saw that there was no documentation available for Remix. Since it's the framework I primarily use, and after playing around for a while, I thought it would be helpful to contribute by adding some basic examples showcasing its usage.

Let me know if I need to improve something or there's something else I can help with!

### CODE REVIEW

**Comment by Eiley2** [comment]
Sorry about that import, I didn't saw it.

**Comment by Bekacru** [comment]
> Sorry about that import, I didn't saw it.

no worries this looks good. If you can please add `remix` section on the integration section. See the other framework docs as an example.

**Comment by Eiley2** [comment]
Sure, working on it right now!

**Comment by Eiley2** [comment]
@Kinfe123 @Bekacru Let me know what you think!

**Comment by Eiley2** [comment]
Saw the error in the CI pipeline and synced my branch with the repo branch, let me know if it works now.

**Comment by Bekacru** [comment]
> Saw the error in the CI pipeline and synced my branch with the repo branch, let me know if it works now.

thanks! good job. please run `pnpm lint:fix` and I'll merge it.

**Comment by Eiley2** [comment]
> > Saw the error in the CI pipeline and synced my branch with the repo branch, let me know if it works now.
> 
> thanks! good job. please run `pnpm lint:fix` and I'll merge it.

Done!

**Pull request merged**
