### PR TITLE
refactor: Use winston for logging

### PR DESCRIPTION
**Pull request by tklein1801**
Created for #124 

I have installed [Winston](https://www.npmjs.com/package/winston) and replaced the logging. Before the branch is merged, the current log format should be removed as well as the question of whether there should be a ‘transport’ for the logs by default.

- [ ] Approve or rework new log format
- [ ] Improve logging (add more logging)
- [ ] Update [documentation](https://www.better-auth.com/docs/introduction)

### CODE REVIEW

**Comment by Bekacru** [comment]
My only objection is that winston feels huge to include with an auth library. It’d be great if we could find a more lightweight alternative.

**Comment by tklein1801** [comment]
I'll take a look around some logging libraries

**Comment by tklein1801** [comment]
@Bekacru could I light your interest in [pino](https://github.com/pinojs/pino/tree/main)? 
Way smaller than winston, actively maintained and does support custom transporting your logs

**Comment by Chris-Kode** [comment]
i have been using the pino library, and its working well for logging, is a good option

**Comment by frasza** [comment]
Pino does sound great tbh.

**Pull request closed without merging**
