### PR TITLE
docs(add): "your first plugin" guide

### PR DESCRIPTION
**Pull request by Multinite**
A guide for first time users at creating a plugin.

### CODE REVIEW

**Comment by ping-maxwell** [comment]
Important: this guide uses links that are only valid to my other docs update for the major refactor of `concepts/plugins`.
[#802](https://github.com/better-auth/better-auth/pull/802)

**Comment by ping-maxwell** [comment]
Sanitization of `birthday` should probably take place in that before hook too huh...

**Comment by Bekacru** [comment]
this is really good!

**Comment by ping-maxwell** [comment]
> this is really good!

Thanks, I really appreciate it!!

**Pull request merged**
