### PR TITLE
fix: mysql migrations with drizzle

### LINKED ISSUE #26: BLOB/TEXT column 'id' used in key specification without a key length
I am getting an error when running the command `npx better-auth migrate` on MySQL Database. This is an example of the `auth.ts` I am using.

```typescript
export const auth = betterAuth({
  database: {
    provider: 'mysql',
    url: 'mysql://root:@127.0.0.1:3306/superOceanDB',
  },
  emailAndPassword: {
    enabled: true,
  },
  user: {
    modelName: 'users',
  },
  account: {
    modelName: 'accounts',
  },
  session: {
    modelName: 'sessions',
  },
});
```

And this is the error that appears in the terminal window:
```bash
...at async CreateTableBuilder.execute (file:///Users/yusuf/Documents/sandbox/next-js/super-ocean/node_modules/kysely/dist/esm/schema/create-table-builder.js:350:9) {
  code: 'ER_BLOB_KEY_WITHOUT_LENGTH',
  errno: 1170,
  sqlState: '42000',
  sqlMessage: "BLOB/TEXT column 'id' used in key specification without a key length",
  sql: 'create table `users` (`id` text primary key, `name` text not null, `email` text not null, `emailVerified` boolean not null, `image` text, `createdAt` date not null, `updatedAt` date not null)'
}

Node.js v20.14.0
```

The error does not occur when running with an SQLite database.

When I debug the generated query,
```sql
CREATE TABLE `users` (
	`id` text PRIMARY KEY,
	`name` text NOT NULL,
	`email` text NOT NULL,
	`emailVerified` boolean NOT NULL,
	`image` text,
	`createdAt` date NOT NULL,
	`updatedAt` date NOT NULL)
```
I get the same error

`Query 1 ERROR at Line 1: : BLOB/TEXT column 'id' used in key specification without a key length`

I suspect this is due to the table schema generator.

### PR DESCRIPTION
**Pull request by gltjk**
fix #26 bug in drizzle migrations using similar solution to #27

### CODE REVIEW

**Comment by Bekacru** [comment]
I think we only need to apply it for `id` and `reference` fields. Other fields can remain `text`.

**Comment by gltjk** [comment]
> I think we only need to apply it for `id` and `reference` fields. Other fields can remain `text`.

Thanks for the reply! I see what you mean but I believe there’s a bit more to it. In MySQL, text fields with unique indexes (like `email` / `username` / `phoneNumber` in `user` table and `token` in `session` table) also throw errors saying "BLOB/TEXT column 'XXX' used in key specification without a key length".

And for those fields without such constraints (like `name` / `ipAddress` / `userAgent` / `accessToken` / `refreshToken`), I think `VARCHAR` is still a better fit. It’s faster to read and sort because it’s stored with the row, while `TEXT` is stored separately, which slows things down. Honestly, I’d only use `TEXT` for something like storing full articles or big chunks of text. For most other fields, `VARCHAR` is simpler, faster, and avoids running into weird MySQL quirks later.

As for the default length for `VARCHAR`, I used 255 in the PR, which is also your choice in #27 . In case that's not long enough, we may also increase it to up to 65535 (already equal to what `TEXT` can hold at most). If that's still not enough, we can then turn to `MEDIUMTEXT` (16MB) or `LONGTEXT` (4GB), but I doubt if any predefined fields in `better-auth` plugins would require that much.

**Comment by Bekacru** [comment]
One field that needs more than 255 characters is the `value` field in the `verification` table, as it can store a stringified JSON value, like an OAuth state, which often exceeds 255 characters. Currently, we don't utilize JSON fields; instead, we use strings to maintain consistency across all dbs. This will limit us not just to use`varchar`. I know we could increase the limit, but at that point, using `text` would be a better option. You're also correct that `unique` values require `varchar` since they need to be indexed. If you look at the Kysely implementation, you'll notice we selectively apply `varchar`.

https://github.com/better-auth/better-auth/blob/main/packages/better-auth/src/db/get-migration.ts#L171

**Comment by gltjk** [comment]
> One field that needs more than 255 characters is the `value` field in the `verification` table, as it can store a stringified JSON value, like an OAuth state, which often exceeds 255 characters. Currently, we don't utilize JSON fields; instead, we use strings to maintain consistency across all dbs. This will limit us not just to use`varchar`. I know we could increase the limit, but at that point, using `text` would be a better option. You're also correct that `unique` values require `varchar` since they need to be indexed. If you look at the Kysely implementation, you'll notice we selectively apply `varchar`.
> 
> https://github.com/better-auth/better-auth/blob/main/packages/better-auth/src/db/get-migration.ts#L171

Thanks for the feedback! I just found the original issue (#26 ) and the solution to it (#27 ), which is why I submitted my PR. I didn’t check the current code thoroughly—that’s on me. I’ve now updated my PR to follow the current Kysely implementation.

**Comment by Bekacru** [comment]
Hey thanks for taking the time and fixing the PR :)) appreciate it!

**Pull request merged**
