### PR TITLE
feat: add `SurrealDB` adapter

### PR DESCRIPTION
**Pull request by oskar-gmerek**
What and why:

As a user I would like to keep my users data in my favorite database - [SurrealDB](https://surrealdb.com).
There is at least two ways to do it: 
- **implement dialect for Kysely** - I have no motivation to do that, I'm not using Kysely and current SurrealDB dialect is outdated
- **implement adapter for Better-Auth** - This is my choice and my attempt to achieve it

Plan:

- [x] Implement adapter
- [x] Make sure that all adapter tests passed
- [x] Create adapter documentation

### CODE REVIEW

**Comment by Bekacru** [comment]
Hi there, thanks for the PR! Could you please add a test SurrealDB instance in the Dockerfile?

**Comment by oskar-gmerek** [comment]
Hi @Bekacru, sure, will do.

**Comment by Bekacru** [comment]
Hey, thanks for the update. Please fix the conflict and will get this merged 🚀

**Comment by oskar-gmerek** [comment]
@Bekacru The conflicts should be resolved now. The branch is currently up to date with main branch.

**Comment by oskar-gmerek** [comment]
@Bekacru I see that adapter was removed before the last release, was something wrong with it?

**Comment by Bekacru** [comment]
There was an issue in CI where the database instance couldn’t be initialized. (VersionRetrievalFailure: Failed to retrieve remote version. If the server is behind a proxy, make sure it’s configured correctly.) It could probably be fixed easily, but I couldn’t resolve it, so I decided to wait for the next release.

**Comment by oskar-gmerek** [comment]
Yes, it can be easily solved by passing flag, do you want me to do another pull request?

**Pull request merged**
