### PR TITLE
feat: restore the user data in the response

### PR DESCRIPTION
**Pull request by wh5938316**
I propose restoring the user data in the response of api.signUpEmail to complete the registration flow in my Nest.js application. Without this change, I am restricted to using versions of better-auth prior to v1.0.23.

The issue I am facing is described in #1036. Importantly, this modification does not break any existing functionality. Notably, the api.signInEmail endpoint already includes the user data in its response (which seems to be an oversight).

I kindly request that this PR be merged as a temporary measure.

### CODE REVIEW

**Comment by Bekacru** [comment]
Hey, thanks for the PR! We can go with this, but could you please add the user data to other endpoints and plugins that generate a new session and only return the `token` as well?

**Comment by wh5938316** [comment]
Sure, happy to help!

By the way, I’d like to discuss something. Based on my understanding of REST API conventions, a POST /sources endpoint typically returns the created resource. Following this logic, signUp creates a user resource, so it makes sense to return the user. Similarly, signIn creates a session resource, so returning the session would be reasonable as well.

Do you agree with this reasoning? If so, I can include the basic session data in the response as part of this PR. If not, I’ll limit this PR to restoring the user data only.

Looking forward to your feedback!

**Comment by wh5938316** [comment]
This approach is also reflected in Supabase’s API design. For example, the auth.signInWithPassword API returns both the session and user data: [Supabase Auth API Reference](https://supabase.com/docs/reference/javascript/auth-signinwithpassword).

**Comment by Bekacru** [comment]
We used to return the entire object. But, we want to avoid this because users can easily extend the tables and might introduce sensitive data that shouldn't be exposed to the user. Returning only the base session fields we provide may not be a bad idea. But for now let's keep it with the user data.

**Comment by wh5938316** [comment]
Hi, @Bekacru 

I’ve added the user data to all endpoints and plugins that generate a new session and previously only returned the token, as requested.

Please let me know if there’s anything else to adjust. If everything looks good, I’d appreciate it if you could merge this PR.

Thank you!

**Comment by wh5938316** [comment]
In addition to the requested changes, I noticed that in the one-tap plugin, the following section of code:

https://github.com/better-auth/better-auth/blob/cc94e6a7c07c5742938a15e6e340d3dde3de17b3/packages/better-auth/src/plugins/one-tap/index.ts#L110-L113

currently returns the complete session in the main branch. I believe this might be an oversight. I have updated it accordingly in this PR, but I recommend giving this specific change an extra review.

Let me know if this aligns with your expectations!

**Comment by Bekacru** [comment]
yeah this looks great. thanks!

**Pull request merged**
