### PR TITLE
Update in basic usage of react in mdx and nextjs template

### PR DESCRIPTION
**Pull request by qamarq**
**In basic usage mdx**:
- Some miss spell like `onsSuccess`
- username input value fix
- added client auth like in docs

**In NextJS Example**:
- removed unused vars and imports
- nextjs `'` escape
- added new method of generating qrcode cause the old one doesn't work at all
- added depedencies to `qrcode` lib

### CODE REVIEW

**Comment by Bekacru** [comment]
Hey, can you run "pnpm lint:fix"

**Comment by qamarq** [comment]
@Bekacru I wish but I can't do that on my Windows cause of * in svelte (I guess) file

**Comment by qamarq** [comment]
All the changes I made on the GitHub site cause I can't clone it on my Windows

**Comment by Kinfe123** [comment]
@qamarq  lemme do it for u

**Comment by qamarq** [comment]
Or wait, I can do it on linux

**Comment by qamarq** [comment]
I do it but anyway. You've already done it

**Comment by qamarq** [comment]
@Kinfe123 I updated demo/nextjs too cause its the same template but in two different directories. I think we need do something with it but for now I pushed the same changes as to example/nextjs

**Comment by qamarq** [comment]
and @Bekacru ?

**Pull request closed without merging**
